default:
  image: node:22-alpine
  interruptible: true
  cache:
    key:
      files: [pnpm-lock.yaml]
    paths:
      - .pnpm-store
      - node_modules/
  variables:
    PNPM_HOME: "/root/.local/share/pnpm"
    PATH: "$PNPM_HOME:$PATH"
  before_script:
    - corepack enable
    - corepack prepare pnpm@10.15.0 --activate
    - pnpm --version
    - pnpm install --frozen-lockfile
